### ISSUE TITLE
Failed to compile on Windows

### ISSUE THREAD

**Issue by perqin** [eycorsican/aleaf#5]
I've installed Visual Studio with C++ Workload, latest Rust stable toolchain, NDK, CMake, and have followed the instruction [here](https://mozilla.github.io/firefox-browser-architecture/experiments/2017-09-21-rust-on-android.html) to build this project. Finally I got the following error:

```
C:\Users\Perqin\Workspaces\project-bamboo\aleaf\app\src\main\rust\leaf-android [master ≡ +1 ~0 -0 !]> cargo build --target aarch64-linux-android --no-default-features --features "leaf/default-ring"
   Compiling leaf v0.1.2 (https://github.com/eycorsican/leaf.git#b2b26d58)
error: failed to run custom build command for `leaf v0.1.2 (https://github.com/eycorsican/leaf.git#b2b26d58)`

Caused by:
  process didn't exit successfully: `C:\Users\Perqin\Workspaces\project-bamboo\aleaf\app\src\main\rust\leaf-android\target\debug\build\leaf-049d01d05a076cf8\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=src/mobile/wrapper.h

  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'clang.dll\', \'libclang.dll\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', C:\Users\Perqin\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\bindgen-0.58.1\src/lib.rs:2057:31
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:493
     1: core::panicking::panic_fmt
               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\core\src\panicking.rs:92
     2: core::option::expect_none_failed
               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\core\src\option.rs:1300
     3: core::result::Result<tuple<>, alloc::string::String>::expect<tuple<>,alloc::string::String>
               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\library\core\src\result.rs:997
     4: core::ops::function::FnOnce::call_once<fn() -> alloc::sync::Arc<clang_sys::SharedLibrary>,tuple<>>
               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\library\core\src\ops\function.rs:227
     5: lazy_static::lazy::{{impl}}::get::{{closure}}<alloc::sync::Arc<clang_sys::SharedLibrary>,fn() -> alloc::sync::Arc<clang_sys::SharedLibrary>>
               at C:\Users\Perqin\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\lazy_static-1.4.0\src\inline_lazy.rs:31
     6: std::sync::once::{{impl}}::call_once::{{closure}}<closure-0>
               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\library\std\src\sync\once.rs:261
     7: std::sync::once::Once::call_inner
               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\sync\once.rs:418
     8: std::sync::once::Once::call_once<closure-0>
               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\library\std\src\sync\once.rs:261
     9: lazy_static::lazy::Lazy<alloc::sync::Arc<clang_sys::SharedLibrary>>::get
               at C:\Users\Perqin\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\lazy_static-1.4.0\src\inline_lazy.rs:30
    10: bindgen::ensure_libclang_is_loaded::{{impl}}::deref::__stability
               at C:\Users\Perqin\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\lazy_static-1.4.0\src\lib.rs:142
    11: bindgen::ensure_libclang_is_loaded::{{impl}}::deref
               at C:\Users\Perqin\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\lazy_static-1.4.0\src\lib.rs:144
    12: bindgen::ensure_libclang_is_loaded
               at C:\Users\Perqin\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\bindgen-0.58.1\src\lib.rs:2065
    13: bindgen::Bindings::generate
               at C:\Users\Perqin\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\bindgen-0.58.1\src\lib.rs:2123
    14: bindgen::Builder::generate
               at C:\Users\Perqin\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\bindgen-0.58.1\src\lib.rs:1434
    15: build_script_build::generate_mobile_bindings
               at .\build.rs:99
    16: build_script_build::main
               at .\build.rs:158
    17: core::ops::function::FnOnce::call_once<fn(),tuple<>>
               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\library\core\src\ops\function.rs:227
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I've googled a little bit and it seems that clang toolchain in NDK can't be used by bindgen.

I also tried to install Clang with Visual Studio and use that one instead, but then I got another error saying that `android/log.h` can't be found.

Are there any mistakes in my build environment?

**Comment by eycorsican** [comment]
I would recommend a Linux host for  compilation.

**Comment by perqin** [comment]
OK, I'll try it later.

**Comment by perqin** [comment]
It does build on Linux and now I see the reason: Android NDK provide libclang.so.11git on Linux, but no any libclang.dll on Windows. I'll try build NDK manually. This issue could be closed now.
